security:
  oauth2:
    client:
      clientId: store-service
      clientSecret: ${STORE_SERVICE_PASSWORD}
      accessTokenUri: http://auth-server:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: store-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: eodessa
      port: 27017

server:
  context-path: /stores
  port: 6100