---
server:
  port: 8888
logging:
  path: /var/log/
#security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: ${CONFIG_SERVICE_PASSWORD}
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#        git:
#          uri: https://github.com/sbruksha/event-driven-microservices-config
#          #username: user
#          #password: pass
#          search-paths:
#          - 'catalog*'
        encrypt:
          enabled: false
  application:
    name: config-server
  profiles:
     active: native

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
    instance-id: ${spring.application.name}_${random.int}:${server.port}
    preferIpAddress: false
    hostname: config-server